default: &default
  validation_framework: :active_model # optional

development:
  <<: *default
  database: http://user:password@localhost:5984/yaws
test:
  <<: *default
  database: test_db_name
production:
  <<: *default
  database: http://user:password@localhost:5984/yaws_prod